services:
  # ==========================
  # Auth Service
  # ==========================
  auth-service:
    build:
      context: .
      dockerfile: user-auth-service/Dockerfile
    depends_on:
      api-gateway:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    env_file:
      - ./user-auth-service/.env.prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    expose:
      - "8081"
    networks:
      - backend

  # ==========================
  # Notification Service
  # ==========================
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      kafka:
        condition: service_started
      consul:
        condition: service_started
    env_file:
      - ./notification-service/.env.prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8087/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    expose:
      - "8087"
    networks:
      - backend

  # ==========================
  # Product Service
  # ==========================
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    depends_on:
      inventory-service:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
      consul:
        condition: service_started
    env_file:
      - ./product-service/.env.prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    expose:
      - "8082"
    networks:
      - backend
  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
      consul:
        condition: service_started
      inventory-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    env_file:
      - ./cart-service/.env.prod
    expose:
      - "8084"
    networks:
      - backend
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    env_file:
      - ./payment-service/.env.prod
    expose:
      - "8085"
    networks:
      - backend
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    env_file:
      - ./order-service/.env.prod
    expose:
      - "8086"
    networks:
      - backend
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
      consul:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    env_file:
      - ./inventory-service/.env.prod
    expose:
      - "8083"
    networks:
      - backend
  consul:
    image: hashicorp/consul:1.15.4
    ports:
      - "8500:8500"
    command: consul agent -dev -client=0.0.0.0
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================
  # Api Gateway
  # ==========================

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=my_secure_password_123!
      - SPRING_PROFILES_ACTIVE=prod
      - CONSUL_HOST=consul
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - backend
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -p 6379 -a ${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    command: redis-server --requirepass ${REDIS_PASSWORD}  # Hardcoded
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    healthcheck:
      test: |
        kafka-broker-api-versions --bootstrap-server localhost:9092 2>/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
    ports:
      - "9093:9093"  # Host:Container port for PLAINTEXT_HOST
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - backend
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      # The command Docker runs inside the container to check its health.
      # 'curl -f' fails silently (returns a non-zero exit code) on server errors.
      test: ["CMD-SHELL", "wget -qO- http://localhost:9411/health || exit 1"]
      interval: 30s       # How often to run the check.
      timeout: 10s        # How long to wait for a response.
      retries: 3          # Number of consecutive failures to be considered "unhealthy".
      start_period: 15s   # Grace period for the container to start before checks begin

volumes:
  redis_data:
networks:
  backend:
    driver: bridge
    attachable: true