spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost        # your Consul agent
      port: 8500             # default Consul port
      enabled: true          # turn Consul on
      discovery:
        enabled: true        # allow discovery via Consul
        register: true       # register this gateway in Consul
    gateway:
      routes:
        # 📦 Route to auth user service
        - id: auth-service
          uri: lb://auth-user-service
          predicates:
            - Path=/api/auth/**,/api/user/**
        # 📦 Route to product service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**,/api/categories/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 # tokens per second (how many requests are allowed per second)
                redis-rate-limiter.burstCapacity: 20 # max tokens (how many requests are allowed in a burst)
                key-resolver: '#{@ipAddressKeyResolver}' # Define how to identify the client (see next step)
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 9000

