spring:
  application:
    name: api-gateway
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
        register: false
    gateway:
      routes:
        # 📦 Route to auth user service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**,/api/user/**
        # 📦 Route to product service
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**,/api/categories/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080