spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  cloud:
    consul:
      host: localhost        # your Consul agent
      port: 8500             # default Consul port
      enabled: true          # turn Consul on
      discovery:
        enabled: true        # allow discovery via Consul
        register: true       # register this gateway in Consul
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.security: DEBUG
cloudinary:
  cloud-name: dooadf4kx
  api-key: 463342149666781
  api-secret: zy9I5PXnWhM9KmHHzlysr-HV-R0

inventory:
  service:
    url: http://localhost:8083

