spring:
  application:
    name: inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:${PUBLIC_KEY_LOCATION}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}  # Must be set via secrets manager
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 15
      minimum-idle: 5
  flyway:
    enabled: true
    clean-disabled: true                  # 🚫 Critical for prod - disable clean!
    validate-on-migrate: true             # ✅ Ensure migration validity
    baseline-on-migrate: false
    out-of-order: false                   # 🚫 Prevent unordered migrations in prod
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      jdbc:
        lob:
          non_contextual_creation: true  # Fix PostgreSQL LOB handling
    show-sql: false                       # 🚫 Disable SQL logging in prod
    properties:
      hibernate:
        generate_statistics: false

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
      group-id: inventory-service-group
      auto-offset-reset: latest           # Prefer latest in prod
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "com.backend.common.events"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      enabled: true
      discovery:
        enabled: true
        register: true
  threads:
    virtual:
      enabled: true
server:
  port: 8083
  error:
    include-message: on_param             # Limit error details
    include-binding-errors: never
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    org.apache.kafka: INFO
  file:
    name: /var/log/inventory-service.log
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 14