name: CI/CD for Multi-Service Spring Boot

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build all modules with Maven
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          # List of services
          SERVICES="user-auth-service product-service cart-service inventory-service notification-service payment-service order-service api-gateway"
          
          for SERVICE in $SERVICES
          do
            IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${SERVICE}:latest
            echo "Building image for $SERVICE..."
            docker build -t $IMAGE_NAME -f ./$SERVICE/Dockerfile .
            docker push $IMAGE_NAME
          done
